# Generated by Django 3.2.9 on 2021-11-09 10:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код учебника')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('sertificate', models.CharField(max_length=9, verbose_name='Сертификат')),
                ('certification_year', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Год сертификации')),
                ('pages', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('pictures', models.PositiveIntegerField(verbose_name='Количество рисунков')),
            ],
            options={
                'verbose_name_plural': 'Учебники',
            },
        ),
        migrations.CreateModel(
            name='BooksSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код раздела учебника')),
                ('name', models.CharField(max_length=50, verbose_name='Название раздела учебника')),
            ],
            options={
                'verbose_name_plural': 'Разделы учебника',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Код кафедры')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование кафедры')),
            ],
            options={
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Код специальности')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Код преподавателя')),
                ('surname', models.CharField(max_length=50, verbose_name='ФИО преподавателя')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.department', verbose_name='Код кафедры')),
            ],
            options={
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код студента')),
                ('surname', models.CharField(max_length=50, verbose_name='ФИО студента')),
                ('transcript_number', models.CharField(max_length=9, verbose_name='Номер зачетной книжки')),
                ('admission_year', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2017, 8, 30))], verbose_name='Год поступления')),
                ('course', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=5, verbose_name='Курс')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.special', verbose_name='Код специальности')),
            ],
            options={
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='GiveBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Дата выдачи учебника')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.book', verbose_name='Учебник')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name_plural': 'Выдача учебников',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=50, verbose_name='Дисциплина')),
                ('course', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=5, verbose_name='Курс')),
                ('semestr', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=5, verbose_name='Семестр')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.special', verbose_name='Специальность')),
            ],
            options={
                'verbose_name_plural': 'Учебный план',
            },
        ),
        migrations.CreateModel(
            name='BooksStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.book', verbose_name='Код учебника')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.bookssection', verbose_name='Код раздела учебника')),
            ],
            options={
                'verbose_name_plural': 'Состав учебника',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.special', verbose_name='Специальность'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.teacher', verbose_name='Код автора')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.book', verbose_name='Код учебника')),
            ],
            options={
                'verbose_name_plural': 'Авторы',
            },
        ),
    ]
